

# File: azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # or your default branch
      - branch3

pool:
  name: 'azure_pool'

variables:
  azureSubscription: 'MyUMI' # Set up in DevOps Service Connections
  appName: 'myapp002'
  #resourceGroup: '<YOUR-RESOURCE-GROUP-NAME>'
  packagePath: '$(Build.SourcesDirectory)'

steps:
# Step 1: Checkout code from GitHub
- task: Checkout@2
  displayName: 'Checkout GitHub repository'


# Step 4: Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux' # since PHP is on Linux runtime
    appName: '$(appName)'
    package: '$(Build.SourcesDirectory)'
