# File: azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - branch3

pool:
  name: 'azure_pool'

variables:
  azureSubscription: 'MyUMI' # DevOps Service Connection
  appName: 'myapp002'

steps:
# Step 1: Checkout code from GitHub
- checkout: self
  displayName: 'Checkout GitHub repository'

# Step 2: Deploy entire repo folder directly to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(Build.SourcesDirectory)'
